### ISSUE TITLE
[Frontend] 翻訳APIを呼びだす

### ISSUE THREAD

**Issue by VU-TUAN-KIET-BENGO4** [tpa-bengo4/Legal-Speech#15]
## 内容
わからないテキストを自分の好きな言語に翻訳する

## 受け入れ条件

- [x] 言語が選べる
- [x] 内容は正しい
- [x] APIの返事期限は３秒以内

## API

- Azure OpenAI Service 35-turbo

**Comment by BUI-DANH-TUNG-BENGO4** [comment]
## **進捗報告：**
**やったこと：**

- [x] 言語を選択するための入力インターフェイスを作成した
- [x] Azure openAI サービスで AI モデルをセットアップした
- [x] Azure openAIから翻訳APIを呼び出すロジックを開発した
- [x] 結果をメッセージ インターフェイスに表示した

**問題：**
Azure openAI は限られた数のモデルでのみ使用できるため、結果を適切にフォーマットするロジックを構築する必要があります。これにはかなり時間がかかります

**次回開発の予定：**

- 翻訳するUIを向上する
- テスト
